/**
 * Given an array arr[] of N positive elements. The task is to find the Maximum AND Value generated by 
 * any pair of element from the array.
 * Note: AND is bitwise '&' operator.
 * 
 * Input:
 * The first line of the input contains a single integer T, denoting the number of test cases. Then T 
 * test cases follow. Each test-case has two lines of the input, the first line contains an integer denoting 
 * the size of an array N and the second line of input contains N positive integers
 * 
 * Output:
 * For each testcase, print Maximum AND Value of a pair in a separate line.
 * 
 * Constraints:
 * 1 <=T <= 100
 * 1 <= N <= 100
 * 1 <= arr[i] <= 104
 * 
 * Example:
 * Input:
 * 2
 * 4
 * 4 8 12 16
 * 4
 * 4 8 16 2
 * 
 * Output:
 * 8
 * 0
 * 
 * Explanation:
 * Testcase 1: Pair (8,12) has the Maximum AND Value  i.e. 8.
 * Testcase 2: Maximum AND Value is 0
 * 
 */
package datastructures.BITManipulation;

import java.util.Scanner;

public class Program12 {

	public static void main(String[] args) {
		Scanner in = new Scanner(System.in);
		try {
			int T = in.nextInt();
			while(T --> 0) {
				int N = in.nextInt();
				int[] arr = new int[N];
				for(int i = 0; i < arr.length; i++) {
					arr[i] = in.nextInt();
				}
				
				int result = 0;
				for(int i = 0; i < arr.length; i++) {
					for(int j = i + 1; j < arr.length; j++) {
						result = result > (arr[i] & arr[j]) ? result : (arr[i] & arr[j]); 
					}
				}
				System.out.println(result);
			}
		} finally {
			if(in != null) {
				in.close();
			}
		}
	}

}
